module.exports = {
    PYTHAGORA_TESTS_DIR: 'pythagora_tests',
    PYTHAGORA_METADATA_DIR: '.pythagora',
    METADATA_FILENAME: 'metadata.json',
    REVIEW_DATA_FILENAME: 'review.json',
    EXPORT_METADATA_FILENAME: 'export.json',
    PYTHAGORA_ASYNC_STORE: 42069420,
    PYTHAGORA_DELIMITER: '-_-',
    EXPORTED_TESTS_DIR: 'pythagora_tests/exported_tests',
    EXPORTED_TESTS_DATA_DIR: 'pythagora_tests/exported_tests/data',
    SRC_TO_ROOT: '../../../',
    MIN_TOKENS_FOR_GPT_RESPONSE: 1640,
    MAX_GPT_MODEL_TOKENS: 8192,
    PYTHAGORA_UNIT_TESTS_VERSION: 1,
    PYTHAGORA_UNIT_DIR: 'pythagora_tests/unit',
}
