let PYTHAGORA_TESTS_DIR = 'pythagora_tests';
let PYTHAGORA_METADATA_DIR = '.pythagora';
let METADATA_FILENAME = 'metadata.json';
let REVIEW_DATA_FILENAME = 'review.json';
let PYTHAGORA_ASYNC_STORE = 42069420;

module.exports = {
    PYTHAGORA_TESTS_DIR,
    PYTHAGORA_METADATA_DIR,
    METADATA_FILENAME,
    REVIEW_DATA_FILENAME,
    PYTHAGORA_ASYNC_STORE
}
